// Generated by CoffeeScript 1.6.1
(function() {
  var Response, check, crypto, getDateStr, reportModel, showPage, userModel, utils;

  crypto = require('crypto');

  check = require('validator').check;

  reportModel = require('../models/reportModel');

  userModel = require('../models/usersModel');

  utils = require('../utils');

  Response = require('../vo/Response').Response;

  exports.index = function(req, res) {
    if (!utils.authenticateUser(req, res)) {
      return;
    }
    //return res.redirect("/show");
	return showPage(req, res, "index");
  };

  exports.writeIndex = function(req, res) {
    if (!utils.authenticateUser(req, res)) {
      return;
    }

    return showPage(req, res, "write");
  };

  exports.edit = function(req, res) {
    if (!utils.authenticateUser(req, res)) {
      return;
    }
	console.log('123456');
	//return res.redirect("/write");
    return showPage(req, res, "write");
  };  
  
  exports.settingMobile = function(req, res) {
    if (!utils.authenticateUser(req, res)) {
      return;
    }
    return res.render("mobile/settings", {
      'title': "设置",
      layout: "mobile/layout.hbs"
    });
  };

  exports.writeIndexMobile = function(req, res) {
    if (!utils.authenticateUser(req, res)) {
      return;
    }
    return showPage(req, res, "mobile/write", {
      'title': "写日报",
      layout: "mobile/layout.hbs",
      "currentDateStr": getDateStr(new Date())
    });
  };

  getDateStr = function(date) {
    var month, today, year;
    today = new Date();
    year = date.getFullYear();
    month = date.getMonth() + 1;
    date = date.getDate();
    return "" + year + "-" + month + "-" + date;
  };

  exports.write = function(req, res) {
    var content, date, dateStr, months, userId, year, _ref;
    if (!utils.authenticateUser(req, res)) {
      return;
    }
    userId = req.session.userId;
    dateStr = req.body.date;
    content = req.body.content;
    try {
      check(dateStr).notEmpty();
      check(content).notEmpty();
      _ref = dateStr.split("-"), year = _ref[0], months = _ref[1], date = _ref[2];
      check(year).notNull().isNumeric().len(4, 4);
      check(months).notNull().isNumeric().len(1, 2);
      //check(date).notNull().isNumeric().len(1, 2);
      return reportModel.createReport(userId, content, dateStr, function(response) {
        return res.send(response);
      });
    } catch (error) {
      return res.send(new Response(0, "wrong date formate！"));
    }
  };
  
  exports.update = function(req, res) {
    var content, date, dateStr, months, userId, year, _ref;
    if (!utils.authenticateUser(req, res)) {
      return;
    }
    userId = req.session.userId;
    dateStr = req.body.date;
    content = req.body.content;
    try {
      check(dateStr).notEmpty();
      check(content).notEmpty();
      _ref = dateStr.split("-"), year = _ref[0], months = _ref[1], date = _ref[2];
      check(year).notNull().isNumeric().len(4, 4);
      check(months).notNull().isNumeric().len(1, 2);
      //check(date).notNull().isNumeric().len(1, 2);
      return reportModel.updateReport(userId, content, dateStr, function(response) {
        return res.send(response);
      });
    } catch (error) {
      return res.send(new Response(0, "wrong date formate！"));
    }
  };  

  exports.showIndex = function(req, res) {
    if (!utils.authenticateUser(req, res)) {
      return;
    }
    return showPage(req, res, "show");
  };

  exports.showIndexMobile = function(req, res) {
    if (!utils.authenticateUser(req, res)) {
      return;
    }
    return showPage(req, res, "mobile/show", {
      'title': "我的日报",
      layout: "mobile/layout.hbs"
    });
  };
 
	getCurrentDateStr = function(date) {
      var month, today, year, day;
	  var month_first, day_first, year_first; // for calc the first day and the last day of the week
	  var month_last, day_last, year_last;
	  
	  date = new Date();
      day = new Date();
	  day_new = new Date();
      year = date.getFullYear();
      month = date.getMonth() + 1;
	  day = date.getDate();
      
	  //return "" + year + "-" + month + "-" + day;  
	  // calc the first day of the week
	  day_new.setDate(date.getDate() - date.getDay() + 4);
	  year_first = day_new.getFullYear();
      month_first = day_new.getMonth() + 1;
	  day_first = day_new.getDate();
	  return "" + year_first + "-" + month_first + "-" + day_first;
	  
    };
    dateStr = getCurrentDateStr(new Date()); 
 
  showPage = function(req, res, pageTitle, data) {
    var userId;
    if (data == null) {
      data = null;
    }
    userId = req.session.userId;
    if (!data) {
      data = {};
    }
    data["hasSubordinate"] = false;
    data["isLoginUser"] = utils.isLoginUser(req);
    data["isAdmin"] = utils.isAdmin(req);
	data["userId"] = userId;
	data["dateStr"] = req.body.date;
	data["userName"] = req.body.userName;
	if (!data["dateStr"]) {
		data["dateStr"] = dateStr;
	}
	
	
	console.log('reportCtr-showPage dateStr:' + data["dateStr"]);
    return userModel.hasSubordinate(userId, function(result) {
      if (result) {
        data["hasSubordinate"] = true;
      }
	  
	  // deal with the init report by check the report exists or not
      return reportModel.hasReport(req, function(result) {
	    if (result) {
	      data["hasReport"] = true;
        }
		
		return reportModel.getReportContent(req, function(result) {
			console.log('reportCtr-reportModel.getReportContent result:' + result);
			if (result) {
				data["content"] = result;
			}
			return res.render(pageTitle, data);
		});
        
	  });
    });
  };

  exports.showsubordinateIndex = function(req, res) {
    var userId;
    if (!utils.authenticateUser(req, res)) {
      return;
    }
    userId = req.session.userId;
    return userModel.hasSubordinate(userId, function(result) {
      if (result) {
        return res.render("showsubordinate", {
          hasSubordinate: true,
          isLoginUser: utils.isLoginUser(req),
          isAdmin: utils.isAdmin(req)
        });
      } else {
        return res.send(new Response(0, '您还没有下属，不需要访问该页面'));
      }
    });
  };

  exports.subordinateIndexMobile = function(req, res) {
    var userId;
    if (!utils.authenticateUser(req, res)) {
      return;
    }
    userId = req.session.userId;
    return userModel.hasSubordinate(userId, function(result) {
      if (result) {
        return res.render("mobile/showsubordinate", {
          title: "下属日报",
          layout: "mobile/layout.hbs",
          hasSubordinate: true,
          isLoginUser: utils.isLoginUser(req),
          isAdmin: utils.isAdmin(req)
        });
      } else {
        return res.send(new Response(0, '您还没有下属，不需要访问该页面'));
      }
    });
  };
  
  exports.getReports = function(req, res) {
    var numOfPage, page, userId;
    if (!utils.authenticateUser(req, res)) {
      return;
    }
    page = req.body.page;
    userId = req.body.userId;
	
	var userAllFlag = '0';
	userAllFlag = req.body.userAllFlag;
	console.log('reportCtr-getReports-userAllFlag:' + userAllFlag);
		
    if (!userId) {
      userId = req.session.userId;
    }
    numOfPage = req.body.numOfPage;
    try {
      check(page).isNumeric().min(1);
      check(page).isNumeric().min(1);
	  
	  if(userAllFlag == '1') {
		return reportModel.getReportsAll(userId, page, numOfPage, function(response) {
          return res.send(response);
        });
	  } else {
		return reportModel.getReports(userId, page, numOfPage, function(response) {
          return res.send(response);
        });
	  }
    } catch (error) {
      return res.send(new Response(0, "页数和每页显示条数为非负数"));
    }
  };

  exports.getReportNum = function(req, res) {
    var userId;
    if (!utils.authenticateUser(req, res)) {
      return;
    }
    userId = req.body.userId;
    if (!userId) {
      userId = req.session.userId;
    }
    return reportModel.getReportNum(userId, function(response) {
      return res.send(response);
    });
  };

  exports["delete"] = function(req, res) {
    var reportId, userId;
    if (!utils.authenticateUser(req, res)) {
      return;
    }
    userId = req.session.userId;
    reportId = req.body.reportId;
    return reportModel.deleteReport(userId, reportId, function(response) {
      return res.send(response);
    });
  };

  exports.getSubordinateUserAndDepartment = function(req, res) {
    var userId;
    if (!utils.authenticateUser(req, res)) {
      return;
    }
    userId = req.session.userId;
    return reportModel.getSubordinateUserAndDepartment(userId, function(response) {
      return res.send(response);
    });
  };

}).call(this);
